### ISSUE TITLE
Reapply tags crashes part way through execution

### ISSUE THREAD

**Issue by XBigTK13X** [XBigTK13X/snowby#28]
```
 return itemsResponse.data.Items.map((item) => (DataClass ? new DataClass(item) : new EmbyItem(item)))
                                 ^

TypeError: Cannot read property 'data' of undefined
    at /common/emby-client.js:127:34
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async cascadeTag (/server/media-tags.js:24:24)
    at async /server/media-tags.js:49:13
```

```
getaddrinfo EAI_AGAIN
```

**Comment by XBigTK13X** [comment]
There is now some error handling around this, but not a fix.

**Comment by XBigTK13X** [comment]
Has something to do with DNS inside docker

**Comment by XBigTK13X** [comment]
I'm seeing the nodejs server making IPv6 requests

**Comment by XBigTK13X** [comment]
In the mean time, I removed the domain based URL for emby and settler, isntead go directly to the IP.
